### ISSUE TITLE
Readme says build folder exists

### ISSUE THREAD

**Issue by sethreidnz** [abidrahmank/OpenCV2-Python-Tutorials#1]
Hi,

The readme says that a build foder exists... But it does not appear to be there. only a source folder. Obviously I can still access you files but would be great to have this explained!

**Comment by abidrahmank** [comment]
hi,

i am sorry about that. It was there earlier. Later it was decided to
include build folder in .gitignore. But i forgot to edit readme. Thank
you for pointing it out.

On 8/6/13, justsayno notifications@github.com wrote:

> Hi,
> 
> The readme says that a build foder exists... But it does not appear to be
> there. only a source folder. Obviously I can still access you files but
> would be great to have this explained!
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/abidrahmank/OpenCV2-Python-Tutorials/issues/1

## 

Abid K.

**Comment by sethreidnz** [comment]
Thats fine. Your python code has been invaluable never the less!

Seth reid

**Comment by sethreidnz** [comment]
I have to say, thank you so much for your code, it has made it imesurably
easier to figure this stuff out as I am learning python while also learning
openCV and trying to get this all to work on a raspberry pi.

Thanks

Seth Reid

On Tue, Aug 6, 2013 at 7:50 PM, Abid K notifications@github.com wrote:

> hi,
> 
> i am sorry about that. It was there earlier. Later it was decided to
> include build folder in .gitignore. But i forgot to edit readme. Thank
> you for pointing it out.
> 
> On 8/6/13, justsayno notifications@github.com wrote:
> 
> > Hi,
> > 
> > The readme says that a build foder exists... But it does not appear to be
> > there. only a source folder. Obviously I can still access you files but
> > would be great to have this explained!
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/abidrahmank/OpenCV2-Python-Tutorials/issues/1
> 
> ## 
> 
> Abid K.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/abidrahmank/OpenCV2-Python-Tutorials/issues/1#issuecomment-22163059
> .

##

**Comment by abidrahmank** [comment]
Thank you for your support !!!

By the way, If you find any mistakes (whether it is small spelling mistakes or big theory or code errors), feel free to correct it and send a PR. I am making these tutorials in a hurry so it is always prone to mistakes (especially since I am a non-English speaker). As a community, we can prepare a good set of tutorials that benefits all.

Regards

Abid K.

**Comment by sethreidnz** [comment]
Yeah I'd be happy to fix up some of the English for you. I will do it when
I have time before my current research scholaship is finished. Would you
want me to just send you how I think it should be worded? On the tutorials
I have done.

Also do you know why there are not cv2 bindings for all of the cv
funcitons. Or is there and google is letting me down. I am trying to find
functions like cv.MoveWindow and cv.SaveImage but I cannot find a
cv2.saveImage or anything like that.

Thanks

Seth

On Thu, Aug 8, 2013 at 4:02 PM, Abid K notifications@github.com wrote:

> Thank you for your support !!!
> 
> By the way, If you find any mistakes (whether it is small spelling
> mistakes or big theory or code errors), feel free to correct it and send a
> PR. I am making these tutorials in a hurry so it is always prone to
> mistakes (especially since I am a non-English speaker). As a community, we
> can prepare a good set of tutorials that benefits all.
> 
> Regards
> 
> Abid K.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/abidrahmank/OpenCV2-Python-Tutorials/issues/1#issuecomment-22300754
> .

##

**Comment by abidrahmank** [comment]
Hi,

I will be really glad if you could send the corrections ASAP. ( I know my English really sucks :) It will be better if you could send it as a Pull Request.

OpenCV was initially made in C. cv functions are python bindings of those C functions. 

Later C++ and its OOP concepts became popular, so OpenCV started migrating to it. So C++ functions were wrapped as cv2 functions. 

So there is no necessity that C and C++ functions are with same name. For example, SaveImage is changed to imwrite (if I remember correctly). So cv.SaveImage() became cv2.imwrite(). cv.LoadImage() became cv2.imread().

These C++ internally depends on old C and they are trying to reduce the dependancy to zero. They are trying to move everything to C++ now and that is OpenCV 3.x is mainly about. They say it makes a lot of things easier. As a result, when OpenCV 3 comes, there will be no cv functions, only cv2. 

Abid K

**Comment by sethreidnz** [comment]
Yes I found that function after a while. It makes it ver confusing
sometimes though! I understand now.

I will try to do it asap. I have no experience using git hub as a commiter
so it would be good practice to do this. I finish my research in oct and
will get it done by then. I also have been workingbon a version of your
contour class that does not pre populatw contour features. This is for
performance reasons on a raspberry pi.

Thanks again. I will help where I can because I feel gratefull for your
help with there tuts.

Regards

Seth
