### ISSUE TITLE
Regarding arguments of cv2.drawContours() 

### ISSUE THREAD

**Issue by levindabhi** [abidrahmank/OpenCV2-Python-Tutorials#170]
Can you please what is significance of every parameters of cv2.drawContours() in readme .

**Comment by Souvikdeb2612** [comment]
Please refer to this OpenCV documentation for understanding the significance of all the parameters. It is pretty clearly explained here:
https://docs.opencv.org/2.4/modules/imgproc/doc/structural_analysis_and_shape_descriptors.html?highlight=drawcontours
