### ISSUE TITLE
Installation instructions for 3.x version

### ISSUE THREAD

**Issue by shubhendusaurabh** [abidrahmank/OpenCV2-Python-Tutorials#27]
I followed the instruction for installing opencv from the tutorials and ended up with 2.4.x version and later encountered problem while going through the instructions.
There is no instruction for installing the 3.x version.
Sourceforge has only 2.4.x branches and Github repo also has only 2.4 branches on master.
It would be nice to have detailed instructions for installing 3.x version.

**Comment by abidrahmank** [comment]
It is for OpenCV 3.x only. But the source file, you need to download from github, not sourceforge. Goto https://github.com/Itseez/opencv, then download zip file in bottom-right corner. 

Or you can install github in your computer, and enter the command `git clone https://github.com/Itseez/opencv.git`. It will download source to your system.
