### ISSUE TITLE
cv2.SIFT() doesn't work in Opencv2.4.9

### ISSUE THREAD

**Issue by arasharchor** [abidrahmank/OpenCV2-Python-Tutorials#61]
Hi I tried your code. it gives an error regarding no module SIFT for cv2 is available while cv2.FeautureDetector_create("SIFT") work. could you let me know why?

**Comment by agude** [comment]
`.sift()` was moved to the [opencv_contrib](https://github.com/opencv/opencv_contrib) repository: https://github.com/opencv/opencv/issues/8232

However, the documentation has not been updated to reflect this.

**Comment by bpkrishnan** [comment]
Install opencv_contrib using

**pip install opencv-contrib-python**

It will work.

**Comment by arasharchor** [comment]
worked like a charm :) Thanks!
