### ISSUE TITLE
a few errors in feature matching articles

### ISSUE THREAD

**Issue by iDevy** [abidrahmank/OpenCV2-Python-Tutorials#7]
Hello, just tried your tutorial on python openCV (doing stuff on pattern matching, and your articles are great!), yet met a few errors:

a call to `cv2.LINE_AA` causes an error - no-module-blah-blah… after digging a little around cv2, found that it should be `cv2.CV_AA`.

Next culprit is `img3 = cv2.drawMatches(img1,kp1,img2,kp2,good,None,**draw_params)` which returns `module object has no attribute 'drawMatches'` and theres no drawMatches method in dir(cv2)... couldnot resolve this one and google is of little help here.

using cv2 version 2.4.7
installed via macports and pip
osx

**Comment by abidrahmank** [comment]
Please use OpenCV 3.x.. Those tutorials are not meant to be used with
OpenCV 2.x.

Abid K.

**Comment by iDevy** [comment]
3.0 is it even released? can't find it anywhere...

**Comment by abidrahmank** [comment]
You have to compile the source with master branch... download it from github.

**Comment by iDevy** [comment]
Thanks! I think this issue can be closed then.

**Comment by mtmarsh2** [comment]
abidrahmank could you give me a quick walkthrough of how to compile the source from the master branch? I downloaded the 3.0 code but I'm not sure what to do next

**Comment by abidrahmank** [comment]
http://docs.opencv.org/trunk/doc/py_tutorials/py_setup/py_table_of_contents_setup/py_table_of_contents_setup.html#py-table-of-content-setup
